# Generated by Django 4.0.4 on 2022-04-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_basequotesymbol_remove_rate_base_quote_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='base_quote_symbol_id',
        ),
    ]
