# Generated by Django 4.0.4 on 2022-04-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_rate_base_quote_symbol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='base_quote_symbol_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.basequotesymbol'),
            preserve_default=False,
        ),
    ]
