# Generated by Django 4.0.4 on 2022-04-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_is_noob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='base_currency_id',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='base_quote_symbol_id',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='quote_currency_id',
        ),
        migrations.RemoveField(
            model_name='wallettype',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type_id',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency_id',
            field=models.ManyToManyField(to='authentication.currency'),
        ),
        migrations.DeleteModel(
            name='BaseQuoteSymbol',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='WalletType',
        ),
    ]
