# Generated by Django 4.0.4 on 2022-04-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.currency'),
            preserve_default=False,
        ),
    ]
