# Generated by Django 4.0.4 on 2022-04-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_main_currency'),
        ('authentication', '0023_alter_user_is_staff'),
    ]

    operations = [
    ]
